heat_template_version: 2016-10-14

description: >
Common neutron port template

parameters:
  network_name:
    type: string
    label: External network name
    description: External network name

  fixed_ip_address:
    type: string
    label: Desired IP for this port.
    description: Desired IP for this port.

  security_group_name:
    type: string
    label: Security group ID
    description: Security group ID to associate with this port

resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network_name}
      fixed_ips:
        - ip_address: {get_param: fixed_ip_address}
      security_groups: [{get_param: security_group_name}]